### ISSUE TITLE
Fix failing test in InitializationCreatorTest

### ISSUE THREAD

**Issue by stefanhechtltng** [TNG/value-provider#1]
InitializationCreatorTest#createSnapshot_should_capture_all_information_to_recreate_a_TestClassInitializationCreator

**Comment by jonashoef** [comment]
I think the failing test shows a production problem with the referenceDateTime read from system properties. Java 9 introduced microsecond time resolution. This, in turn, requires truncating the resolution to milliseconds to allow capturing the referenceDateTime in a single long in the InitializationCreatorSnapshot. 
I therefore fixed the implementation to ensure truncating the referenceDateTime regardless of its source ('now()' or system property). It is especially required for the system property, as this is specified by the user and could therefore have any resolution that the format for parsing allows.
