### ISSUE TITLE
Make helper methods for extending from ValueProvider accessible

### ISSUE THREAD

**Issue by stefanhechtltng** [TNG/value-provider#12]
The preferred way to include value-provider in one's code base is to extend from the ValueProvider (base) class and write one's own methods (on top of the existing methods).
Many core methods rely on the following methods:
- getPrefix()
- getSuffix()
- getRandom()

Extend visibility of said methods to protected, thus ensuring all tools are available for writing new methods in the extending class

**Comment by jonashoef** [comment]
Changes merged
