### ISSUE TITLE
ValueProvider.localTime() throws DateTimeException

### ISSUE THREAD

**Issue by totenn** [TNG/value-provider#24]
The current implementation
`return LocalTime.ofSecondOfDay(longNumber(0, secondsPerDay));`
Throws a DateTimeException when `longNumber(0, secondsPerDay)` returns `secondsPerDay`, which is out of bounds.

**Comment by jonashoef** [comment]
Hi Tobias, 
thank you very much for spotting the problem and providing the fix.
