### ISSUE TITLE
`positiveBigIntegerNumber()` only ever returns numbers that could also be represented as a `long`.

### ISSUE THREAD

**Issue by totenn** [TNG/value-provider#27]
The current implementation for `randomBigIntegerNumber()` uses `Random.nextLong()` for randomness. This has the following downsides:
* `positiveBigIntegerNumber()` can only return values that can also be represented as `long`. But being unable to deal with larger `BigIntegers` is a typical failure case.
* Differences between `randomBigIntegerNumber()`s can also always fit in a `long`. Same issue as above.
* The distribution of numbers is linear. This leads to a bias towards larger numbers. For many applications, a logarithmic distribution would be preferable, so that both large and small numbers can appear in the output with similar probability.

Proposed solution: A very simple approach would be just to use a random `long` and interpret its bits as a `double`, then converting the `double` to a `BigInteger`. This would look somewhat like this:

```
    private BigInteger randomBigIntegerNumber(BigInteger min, BigInteger max) {
        if (max.compareTo(min) <= 0) {
            return min;
        }
        BigInteger diff = max.subtract(min).add(BigInteger.ONE);
        double randomDouble = Double.longBitsToDouble(random.nextLong());
        while (Double.isNaN(randomDouble) || !Double.isFinite(randomDouble)) {
            randomDouble = Double.longBitsToDouble(random.nextLong());
        }
        BigInteger randomDiff = BigDecimal.valueOf(randomDouble).toBigInteger().mod(diff);
        return min.add(randomDiff);
    }
```

It's kind of a hack, but it should have the desired properties and be good enough for test data.

Please let me know what you think. This is just an idea. 
In the end, the only thing that would be really important to me is that `positiveBigIntegerNumber()` also returns large values >> `Long.MAX_VALUE`.

**Comment by jonashoef** [comment]
Well spotted, admittedly a substantial limitation. Thank you for the detailed description and the proposal for fixing it. 
Just another idea: multiply the calculated diff with `random.nextDouble()` (provides double between 0.0 and 1.0). Wouldn't that yield the desired result as well?

**Comment by totenn** [comment]
Hi Jonas,
I think that would be a solution for `randomBigIntegerNumber(min ,max)`, but it wouldn't satisfy my wish to have a non-uniform distribution for `positiveBigIntegerNumber()`.

Perhaps `positiveBigIntegerNumber()` could also be implemented by generating a random exponent `double e = random.nextDouble() * 300`, and then taking `BigDecimal.valueOf(exp(e)).toBigInteger()`.
