### ISSUE TITLE
Provide methods for generating random dates

### ISSUE THREAD

**Issue by stefanhechtltng** [TNG/value-provider#5]
The API should enable the user to specify a timeframe for the date to lie within.

Possible use cases:

* I want a date up to 5 years in the past
* I want a date up to 30 days in the past
* I want a date up to 5 years in the future
* I want a date up to 30 days in the future
* I want a date before the year 2010
* I want a date after the year 2030
* I want a date within 1st of Jan. 2015 and 1st of July 2016

consider similar use cases as well

**Comment by jonashoef** [comment]
Provided by PR #34 / release [1.2.3](https://github.com/TNG/value-provider/releases/tag/v1.2.3)
